var findBtn=function(a,b){var c=this;this.el=$(a).click(function(){c.click()});this.label=$("dd",this.el).text();this.onchange=b};
findBtn.prototype={click:function(){stationsList.control=this;stationsList.show(this.el)},select:function(a){"string"==typeof a&&(a=stationsList.stations[stationsList.index[a]]);if(a!=this.selected){var b=a?a.title:this.label;$("em",this.el).get(0).className=a?a.lname:"empty";$("dl",this.el).toggleClass("selected",Boolean(a));$("dd",this.el).text(b);$("dt",this.el).text(b);this.selected=a;if("function"==typeof this.onchange)this.onchange()}}};with(String)prototype.contains=function(a){return-1<this.indexOf(a)};
var stationsList={init:function(a){var b=this;this.el=$("#stations").mousedown(function(a){a.stopPropagation()});this.field=$(".search input",this.el).data("lastValue","").val("");this.field.keydown(function(a){b.hotkey(a)}).keyup(function(){b.filter()});this.clear=$(".search .clear",this.el).click(function(){b.reset()});this.stations=[];this.index={};var c=this;$(".items li",this.el).each(function(b){var d={id:a[b]};d.lname=d.id.substr(0,3);d.sname=d.id.substr(4);d.el=$(this).addClass(d.lname);d.title=
d.el.text();d.sample=c.getSmartSample(d.title);c.stations[b]=d;c.index[d.id]=b});this.list=$(".list",this.el).click(function(a){a=$(a.target);a.is("ul.items li")?b.select(a.get(0)):a.is("ul.reset li")&&b.select()});this.empty=$(".empty",this.list);this.items=$(".items",this.list);this.scroller.init(this.list);this.hideSelf=function(a){a.data.self.hide()}},reset:function(){this.field.val("");this.filter();this.field.focus()},getSample:function(a){return" "+a.toLowerCase().replace(/\-/g," ").replace(/\u0451/g,
"\u0435")},getSmartSample:function(a){a=this.getSample(a);a.contains("\u0438\u043c.")&&(a+=a.replace("\u0438\u043c.","\u0438\u043c\u0435\u043d\u0438"));a.contains("\u0437\u044c\u043c")&&(a+=a.replace("\u0437\u044c\u043c","\u0437\u043c"));a.contains("1905")&&(a+=a.replace("1905","905"));return a+a.rus2lat()},filter:function(){var a=this.field.val();if(this.field.data("lastValue")!=a){var b=a?this.getSample(a).replace("{","[").replace('"',"'").replace("<",",").replace(">",","):null,c=0;$(this.stations).each(function(){var a=
!b||this.sample.contains(b);$(this.el).css("display",a?"":"none");a&&c++});this.clear.toggle(Boolean(a));this.prefer(null);this.empty.toggle(0==c);this.items.toggle(0<c);this.scroller.el.scrollTop(0);this.scroller.update();this.scroller.toggle();1==c&&this.pass("next")}this.field.data("lastValue",a)},select:function(a){var b=null;"string"==typeof a?b=this.stations[this.index[a]]:a&&(b=this.stations[$(a).prevAll("li").length]);(a=this.control)&&"function"==typeof a.select&&a.select(b);this.hide()},
prefer:function(a){$(this.preferred).removeClass("preferred");a&&($(a).addClass("preferred"),this.scroller.el.scrollToNode(a,15));this.preferred=a},pass:function(a){var b=this.preferred;(a=b?$(b)[a+"All"]("li:visible").get(0):$(".items li:visible:first",this.el).get(0))&&this.prefer(a)},hotkey:function(a){var b=a.which;63232==b&&(b=38);63233==b&&(b=40);switch(b){case 38:this.pass("prev");a.preventDefault();break;case 40:this.pass("next");a.preventDefault();break;case 13:this.preferred&&this.select(this.preferred);
break;case 27:this.field.blur(),this.hide()}},show:function(a){this.prefer(null);this.scroller.el.scrollTop(0);a=$(a);var b=a.offset(),c=this.el.offsetParent().offset(),e=b.left+Math.round(a.width()/2)-120-c.left;a=b.top+Math.round(a.height()/2)-20-c.top;this.el.css("left",e).css("top",a).css("visibility","visible");$("body").bind("mousedown",{self:this},this.hideSelf);this.field.focus()},hide:function(){$("body").unbind("mousedown",this.hideSelf);this.el.css("visibility","hidden");this.field.val("").blur();
this.filter();this.control=null},scroller:{init:function(a){var b=this;this.el=$(".scroll",a).scroll(function(){b.toggle()});this.up=a.find(".up");this.down=a.find(".down");this.up.add(this.down).mouseover(function(a){b.scroll(a)}).mouseout(function(){b.stop()});this.update();this.toggle()},toggle:function(){var a=this.el.scrollTop();this.up.toggle(0<a);this.down.toggle(a<this.max)},update:function(){this.max=this.el.get(0).scrollHeight-this.el.height()},stop:function(){clearInterval(this.timer);
this.animation=!1;this.direction=0},scroll:function(a){a=$(a.target);a.hasClass("up")&&(this.aim=0,this.direction=-1);a.hasClass("down")&&(this.aim=this.max,this.direction=1);var b=this;this.speed=1;this.timer=setInterval(function(){b.step()},25)},step:function(){var a=this.el.scrollTop(),a=a+Math.round(this.direction*this.speed);21>this.speed&&(this.speed+=0.25);0>=a&&(a=0,this.stop());a>=this.max&&(a=this.max,this.stop());this.el.scrollTop(a)}}},kbChars={};
(function(){for(var a=33;a--;)kbChars["\u0439\u0446\u0443\u043a\u0435\u043d\u0433\u0448\u0449\u0437\u0445\u044a\u0444\u044b\u0432\u0430\u043f\u0440\u043e\u043b\u0434\u0436\u044d\u0451\u044f\u0447\u0441\u043c\u0438\u0442\u044c\u0431\u044e".charAt(a)]="qwertyuiop[]asdfghjkl;'\\zxcvbnm,.".charAt(a)})();String.prototype.rus2lat=function(){for(var a=[],b=this.valueOf(),c=0,e=b.length;c<e;c++){var d=b.charAt(c);a.push(kbChars[d]||d)}return a.join("")};
$.fn.scrollToNode=function(a,b){var c=b||0,e=$(this);a=$(a);var d=a.position().top,f=e.height()-a.height();d<c?e.scrollTop(e.scrollTop()+d-c):d>f-c&&e.scrollTop(e.scrollTop()+d-f+c);return this};